export {
  channels,
  eventChannels,
  isChannel,
  isEventChannel,
  type Channel,
  type EventChannel,
} from './channels.js';
export {
  eventContracts,
  WindowMaximizedChangedSchema,
  type EventContracts,
  type EventPayloadOf,
  type WindowMaximizedChanged,
} from './events.js';
export {
  err,
  ok,
  ErrorActionSchema,
  FixoraErrorCodeSchema,
  FixoraErrorSchema,
  type ErrorAction,
  type FixoraError,
  type FixoraErrorCode,
  type Result,
} from './errors.js';
export {
  AppInfoSchema,
  contracts,
  type AppInfo,
  type Contracts,
  type RequestOf,
  type ResponseOf,
} from './ipc.js';
export {
  DirEntrySchema,
  FileContentSchema,
  FilesChangedSchema,
  WorkspaceSchema,
  type DirEntryInfo,
  type FileContentInfo,
  type FilesChanged,
  type WorkspaceInfo,
} from './workspace.js';
export {
  AnalysisStateSchema,
  CategorySchema,
  EvidenceSchema,
  FindingSchema,
  FindingSourceSchema,
  FindingsFilterSchema,
  FindingsSummarySchema,
  LanguageSchema,
  LocationSchema,
  SeveritySchema,
  SymbolKindSchema,
  SymbolRefSchema,
  type AnalysisState,
  type Category,
  type Evidence,
  type Finding,
  type FindingSource,
  type FindingsFilter,
  type FindingsSummary,
  type Language,
  type Location,
  type Severity,
  type SymbolKind,
  type SymbolRef,
} from './analysis.js';
export { FindingsAddedSchema, type FindingsAdded } from './events.js';
export {
  FREE_LICENSE,
  LicensePayloadSchema,
  LicenseStatusSchema,
  type LicensePayload,
  type LicenseStatus,
} from './license.js';
export {
  AI_MODEL_OPTIONS,
  AiConfigSchema,
  AiDeltaSchema,
  AiProposalSchema,
  AiRunRequestSchema,
  AiRunResponseSchema,
  AiRunStateSchema,
  ApplyRepairRequestSchema,
  DEFAULT_AI_MODEL,
  RETIRED_AI_MODELS,
  resolveModelId,
  GateMatchInfoSchema,
  RepairHistoryEntrySchema,
  RepairOutputSchema,
  RepairTargetSchema,
  TaskProfileSchema,
  TestOutputSchema,
  VerdictSchema,
  VerificationReportSchema,
  type AiConfig,
  type AiDelta,
  type AiProposal,
  type AiRunRequest,
  type AiRunResponse,
  type AiRunState,
  type ApplyRepairRequest,
  type GateMatchInfo,
  type RepairHistoryEntry,
  type RepairOutput,
  type TaskProfile,
  type TestOutput,
  type Verdict,
  type VerificationReport,
} from './ai.js';
