export { UserFacingError, isUserFacingError } from './user-facing-error.js';
export {
  channels,
  eventChannels,
  isChannel,
  isEventChannel,
  type Channel,
  type EventChannel,
} from './channels.js';
export {
  eventContracts,
  WindowMaximizedChangedSchema,
  type EventContracts,
  type EventPayloadOf,
  type WindowMaximizedChanged,
} from './events.js';
export {
  err,
  ok,
  ErrorActionSchema,
  FixoraErrorCodeSchema,
  FixoraErrorSchema,
  type ErrorAction,
  type FixoraError,
  type FixoraErrorCode,
  type Result,
} from './errors.js';
export {
  AppInfoSchema,
  contracts,
  type AppInfo,
  type Contracts,
  type RequestOf,
  type ResponseOf,
} from './ipc.js';
export {
  DirEntrySchema,
  FileContentSchema,
  FilesChangedSchema,
  WorkspaceSchema,
  type DirEntryInfo,
  type FileContentInfo,
  type FilesChanged,
  type WorkspaceInfo,
} from './workspace.js';
export {
  AnalysisStateSchema,
  AutofixEditSchema,
  AutofixSchema,
  CategorySchema,
  EvidenceSchema,
  FindingSchema,
  FindingSourceSchema,
  FindingsFilterSchema,
  FindingsSummarySchema,
  LanguageSchema,
  LocationSchema,
  RepairStrategySchema,
  SeveritySchema,
  SymbolKindSchema,
  SymbolRefSchema,
  type AnalysisState,
  type Autofix,
  type AutofixEdit,
  type Category,
  type Evidence,
  type Finding,
  type FindingSource,
  type FindingsFilter,
  type FindingsSummary,
  type Language,
  type Location,
  type RepairStrategy,
  type Severity,
  type SymbolKind,
  type SymbolRef,
} from './analysis.js';
export { FindingsAddedSchema, type FindingsAdded } from './events.js';
export {
  FREE_LICENSE,
  LicensePayloadSchema,
  LicenseStatusSchema,
  type LicensePayload,
  type LicenseStatus,
} from './license.js';
export {
  SUGGESTION_CATEGORY_LABELS,
  SUGGESTION_MESSAGE_MAX_LENGTH,
  SUGGESTION_MESSAGE_MIN_LENGTH,
  ShareSuggestionResponseSchema,
  ShareViaGmailResponseSchema,
  SubmitSuggestionRequestSchema,
  SuggestionCategorySchema,
  SuggestionSchema,
  type Suggestion,
  type SuggestionCategory,
  type ShareSuggestionResponse,
  type ShareViaGmailResponse,
  type SubmitSuggestionRequest,
} from './suggestions.js';
export {
  AiConfigSchema,
  AiDeltaSchema,
  AiProposalSchema,
  AiRunRequestSchema,
  AiFailureSchema,
  AiRunResponseSchema,
  AiRunStageSchema,
  RepairModeSchema,
  RepairSummarySchema,
  RepairSummaryEntrySchema,
  RootCauseInfoSchema,
  AiRunStateSchema,
  ApplyRepairRequestSchema,
  UNRESOLVED_MODEL,
  AiModelListSchema,
  AiModelOptionSchema,
  ApplyOutcomeSchema,
  ApplyFailureReasonSchema,
  StaleRangeCheckSchema,
  VerificationDiagnosticsSchema,
  ModelCatalogueSourceSchema,
  GateMatchInfoSchema,
  RepairHistoryAttemptSchema,
  RepairHistoryEntrySchema,
  RepairOutputSchema,
  RepairTargetSchema,
  FormatterGateSchema,
  NewFindingSchema,
  SyntaxErrorSchema,
  TaskProfileSchema,
  TestOutputSchema,
  EditIntentSchema,
  EditOutputSchema,
  ProceedRunRequestSchema,
  ProceedProposalSchema,
  ProceedOutcomeSchema,
  VerdictSchema,
  VerificationReportSchema,
  type AiConfig,
  type FormatterGate,
  type NewFinding,
  type SyntaxErrorInfo,
  type AiModelList,
  type AiModelOption,
  type ApplyOutcome,
  type ApplyFailureReason,
  type StaleRangeCheck,
  type VerificationDiagnostics,
  type ModelCatalogueSource,
  type AiDelta,
  type AiProposal,
  type AiRunRequest,
  type AiFailure,
  type AiFailureCategory,
  type AiRecoveryAction,
  type AiRunResponse,
  type AiRunStage,
  type RepairMode,
  type RepairSummary,
  type RepairSummaryEntry,
  type RootCauseInfo,
  type AiRunState,
  type ApplyRepairRequest,
  type GateMatchInfo,
  type RepairHistoryAttempt,
  type RepairHistoryEntry,
  type RepairOutput,
  type TaskProfile,
  type TestOutput,
  type EditIntent,
  type EditOutput,
  type ProceedRunRequest,
  type ProceedProposal,
  type ProceedOutcome,
  type Verdict,
  type VerificationReport,
} from './ai.js';

export {
  isRepairSupportedPath,
  isRepairAttemptable,
  repairStateFor,
  REPAIR_STATE_LABEL,
  REPAIR_STATE_REASON,
  type RepairState,
} from './repair-support.js';

export { classifyDiagnostic, type ConfigDiagnosis } from './diagnostic-classifier.js';

export { grammarFor, type GrammarId } from './grammar.js';

export {
  detectDependentFailure,
  isDependencyShapedRule,
  type DependentFailure,
  type PatchRange,
} from './dependent-failure.js';

export {
  categoryRank,
  classifyFinding,
  countByCategory,
  FINDING_CATEGORY_LABEL,
  FINDING_CATEGORY_ORDER,
  type FindingCategory,
  type FindingClassification,
} from './finding-category.js';

export {
  REPAIR_METRICS_LIMIT,
  RepairMetricSchema,
  RepairOutcomeSchema,
  RepairFailureReasonSchema,
  ValidationResultSchema,
  type RepairMetric,
  type RepairOutcome,
  type RepairFailureReason,
  type ValidationResult,
} from './repair-metrics.js';
