export { UserFacingError, isUserFacingError } from './user-facing-error.js';
export {
  channels,
  eventChannels,
  isChannel,
  isEventChannel,
  type Channel,
  type EventChannel,
} from './channels.js';
export {
  eventContracts,
  WindowMaximizedChangedSchema,
  UpdateAvailableSchema,
  UpdateProgressSchema,
  UpdateDownloadedSchema,
  UpdateErrorSchema,
  AppJustUpdatedSchema,
  TerminalDataSchema,
  TerminalExitSchema,
  WorkspaceLargeProjectSchema,
  type EventContracts,
  type EventPayloadOf,
  type WindowMaximizedChanged,
  type UpdateAvailable,
  type UpdateProgress,
  type UpdateDownloaded,
  type UpdateError,
  type AppJustUpdated,
  type TerminalData,
  type TerminalExit,
  type WorkspaceLargeProject,
} from './events.js';
export {
  err,
  ok,
  ErrorActionSchema,
  FixoraErrorCodeSchema,
  FixoraErrorSchema,
  type ErrorAction,
  type FixoraError,
  type FixoraErrorCode,
  type Result,
} from './errors.js';
export {
  AppInfoSchema,
  contracts,
  type AppInfo,
  type Contracts,
  type RequestOf,
  type ResponseOf,
} from './ipc.js';
export {
  DirEntrySchema,
  FileContentSchema,
  FileEncodingSchema,
  FilesChangedSchema,
  WorkspaceSchema,
  type DirEntryInfo,
  type FileContentInfo,
  type FileEncodingName,
  type FilesChanged,
  type WorkspaceInfo,
} from './workspace.js';
export {
  AnalysisStateSchema,
  AnalysisWarningSchema,
  AutofixEditSchema,
  AutofixSchema,
  CategorySchema,
  EvidenceSchema,
  FindingSchema,
  FindingSourceSchema,
  FindingsFilterSchema,
  FindingsSummarySchema,
  LanguageSchema,
  LocationSchema,
  RepairStrategySchema,
  SeveritySchema,
  SymbolKindSchema,
  SymbolRefSchema,
  type AnalysisState,
  type AnalysisWarning,
  type Autofix,
  type AutofixEdit,
  type Category,
  type Evidence,
  type Finding,
  type FindingSource,
  type FindingsFilter,
  type FindingsSummary,
  type Language,
  type Location,
  type RepairStrategy,
  type Severity,
  type SymbolKind,
  type SymbolRef,
} from './analysis.js';
export { FindingsAddedSchema, type FindingsAdded } from './events.js';
export {
  PlanSchema,
  LicenseValidateResultSchema,
  type Plan,
  type LicenseValidateResult,
} from './license.js';
export {
  SUGGESTION_CATEGORY_LABELS,
  SUGGESTION_MESSAGE_MAX_LENGTH,
  SUGGESTION_MESSAGE_MIN_LENGTH,
  ShareSuggestionResponseSchema,
  ShareViaGmailResponseSchema,
  SubmitSuggestionRequestSchema,
  SuggestionCategorySchema,
  SuggestionSchema,
  type Suggestion,
  type SuggestionCategory,
  type ShareSuggestionResponse,
  type ShareViaGmailResponse,
  type SubmitSuggestionRequest,
} from './suggestions.js';
export {
  AiConfigSchema,
  AiDeltaSchema,
  AiProposalSchema,
  AiRunRequestSchema,
  FOLLOWUP_MAX_MESSAGES,
  AiFailureSchema,
  AiRunResponseSchema,
  AiRunStageSchema,
  RepairModeSchema,
  RepairSummarySchema,
  RepairSummaryEntrySchema,
  RootCauseInfoSchema,
  AiRunStateSchema,
  ApplyRepairRequestSchema,
  UNRESOLVED_MODEL,
  AiModelListSchema,
  AiModelOptionSchema,
  ApplyOutcomeSchema,
  BulkRepairStartSchema,
  BulkRepairFlushSchema,
  BulkRepairFlushResultSchema,
  ApplyFailureReasonSchema,
  StaleRangeCheckSchema,
  VerificationDiagnosticsSchema,
  ModelCatalogueSourceSchema,
  GateMatchInfoSchema,
  RepairHistoryAttemptSchema,
  VerifyAttemptSchema,
  RepairHistoryEntrySchema,
  RepairStatsSchema,
  RepairOutputSchema,
  RepairTargetSchema,
  FormatterGateSchema,
  NewFindingSchema,
  SyntaxErrorSchema,
  TaskProfileSchema,
  TestOutputSchema,
  EditIntentSchema,
  EditOutputSchema,
  ProceedRunRequestSchema,
  ProceedProposalSchema,
  ProceedOutcomeSchema,
  VerdictSchema,
  VerificationReportSchema,
  type AiConfig,
  type FormatterGate,
  type NewFinding,
  type SyntaxErrorInfo,
  type AiModelList,
  type AiModelOption,
  type ApplyOutcome,
  type BulkRepairStart,
  type BulkRepairFlush,
  type BulkRepairFlushResult,
  type ApplyFailureReason,
  type StaleRangeCheck,
  type VerificationDiagnostics,
  type ModelCatalogueSource,
  type AiDelta,
  type AiProposal,
  type AiRunRequest,
  type AiFailure,
  type AiFailureCategory,
  type AiRecoveryAction,
  type AiRunResponse,
  type AiRunStage,
  type RepairMode,
  type RepairSummary,
  type RepairSummaryEntry,
  type RootCauseInfo,
  type AiRunState,
  type ApplyRepairRequest,
  type GateMatchInfo,
  type RepairHistoryAttempt,
  type VerifyAttempt,
  type RepairHistoryEntry,
  type RepairStats,
  type RepairOutput,
  type TaskProfile,
  type TestOutput,
  type EditIntent,
  type EditOutput,
  type ProceedRunRequest,
  type ProceedProposal,
  type ProceedOutcome,
  type Verdict,
  type VerificationReport,
} from './ai.js';
export {
  ZapprStepTypeSchema,
  ZapprStepSchema,
  ZapprPlanSchema,
  type ZapprStepType,
  type ZapprStep,
  type ZapprPlan,
} from './zappr.js';

export {
  isRepairSupportedPath,
  isRepairAttemptable,
  repairStateFor,
  REPAIR_STATE_LABEL,
  REPAIR_STATE_REASON,
  type RepairState,
} from './repair-support.js';
export { neighbourRelevanceScore } from './neighbour-relevance.js';

export {
  McpToolNameSchema,
  McpGetFindingsResponseSchema,
  McpTriggerAnalysisResponseSchema,
  McpAnalyzeFileRequestSchema,
  McpAnalyzeFileResponseSchema,
  McpRepairFindingRequestSchema,
  McpRepairFindingResponseSchema,
  McpGetStatusResponseSchema,
  type McpToolName,
  type McpTool,
  type McpRequest,
  type McpResponse,
  type McpGetFindingsResponse,
  type McpTriggerAnalysisResponse,
  type McpAnalyzeFileRequest,
  type McpAnalyzeFileResponse,
  type McpRepairFindingRequest,
  type McpRepairFindingResponse,
  type McpGetStatusResponse,
} from './mcp.js';

export {
  ShieldCategorySchema,
  ShieldSeveritySchema,
  ShieldIssueSchema,
  ShieldCheckSchema,
  PrReadinessSchema,
  CodeShieldReportSchema,
  ShieldSensitivitySchema,
  ShieldSettingsSchema,
  type ShieldCategory,
  type ShieldSeverity,
  type ShieldIssue,
  type ShieldCheck,
  type PrReadiness,
  type CodeShieldReport,
  type ShieldSensitivity,
  type ShieldSettings,
} from './shield.js';

export { classifyDiagnostic, type ConfigDiagnosis } from './diagnostic-classifier.js';

export { grammarFor, type GrammarId } from './grammar.js';

export {
  ProviderInfoSchema,
  ProviderListSchema,
  type ProviderInfo,
  type ProviderList,
} from './providers.js';

export {
  SearchMatchSchema,
  SearchResponseSchema,
  type SearchMatch,
  type SearchResponse,
} from './search.js';

export { PROJECT_TEMPLATES, type ProjectTemplate } from './project-templates.js';

export {
  ManifestKindSchema,
  PackageDependencySchema,
  PackageListSchema,
  PackageSearchResultSchema,
  PackageSearchResponseSchema,
  type ManifestKind,
  type PackageDependency,
  type PackageList,
  type PackageSearchResult,
  type PackageSearchResponse,
} from './packages-manager.js';

export {
  canProbe,
  formatAgo,
  healthColour,
  statusFromFailure,
  statusFromProbe,
  statusLabel,
  MIN_PROBE_INTERVAL_MS,
  ProviderHealthSchema,
  ProviderStatusSchema,
  type HealthColour,
  type ProviderHealth,
  type ProviderStatus,
} from './provider-health.js';

export {
  diagnoseFailure,
  formatResetIn,
  type CheckStatus,
  type DiagnosticCheck,
  type FailureDiagnosis,
} from './failure-diagnosis.js';

export {
  detectDependentFailure,
  isDependencyShapedRule,
  type DependentFailure,
  type PatchRange,
} from './dependent-failure.js';

export {
  detectLintOnlyFailure,
  isLintSource,
  type LintOnlyFailure,
} from './lint-only-failure.js';

export {
  categoryRank,
  classifyFinding,
  countByCategory,
  countByExtension,
  type ExtensionCount,
  FINDING_CATEGORY_LABEL,
  FINDING_CATEGORY_ORDER,
  type FindingCategory,
  type FindingClassification,
} from './finding-category.js';

export {
  REPAIR_METRICS_LIMIT,
  RepairMetricSchema,
  RepairOutcomeSchema,
  RepairFailureReasonSchema,
  ValidationResultSchema,
  type RepairMetric,
  type RepairOutcome,
  type RepairFailureReason,
  type ValidationResult,
} from './repair-metrics.js';
