 apps/desktop/electron-builder.yml                  |  23 [32m+[m[31m-[m
 apps/desktop/electron/acceptance/run.ts            |  26 [32m+[m
 apps/desktop/electron/main/ai/ai-service.ts        | 127 [32m++++[m[31m-[m
 .../desktop/electron/main/ai/repair-eligibility.ts |  24 [32m+[m[31m-[m
 .../electron/main/analysis/analysis-host.ts        |  12 [32m+[m
 .../main/verification/verification-service.ts      |   3 [32m+[m
 apps/desktop/electron/main/windows/main-window.ts  |   4 [32m+[m[31m-[m
 apps/desktop/electron/workers/analysis-worker.mjs  | 536 [32m++++++++++++[m[31m---------[m
 apps/desktop/package.json                          |   2 [32m+[m[31m-[m
 .../desktop/src/features/ai/repair-result.test.tsx |  39 [32m+[m[31m-[m
 apps/desktop/src/features/ai/repair-result.tsx     | 386 [32m+++++++[m[31m--------[m
 .../src/features/ai/verdict-banner.test.tsx        |   2 [32m+[m[31m-[m
 .../src/features/findings/problem-details.tsx      |  60 [32m++[m[31m-[m
 .../src/features/settings/settings-panel.tsx       |   6 [32m+[m[31m-[m
 .../src/features/shell/splash-screen.test.tsx      |  42 [32m++[m
 apps/desktop/src/features/shell/splash-screen.tsx  |  13 [32m+[m[31m-[m
 apps/desktop/src/features/shell/use-splash.test.ts |   2 [32m+[m[31m-[m
 .../src/features/workspace/file-tree.test.tsx      |   3 [32m+[m[31m-[m
 .../src/features/workspace/workspace-store.ts      |   1 [32m+[m
 apps/desktop/src/stores/ai-store.test.ts           |  79 [32m+++[m
 apps/desktop/src/stores/ai-store.ts                |  50 [32m+[m[31m-[m
 apps/desktop/tests/ai-service-failover.test.ts     |   9 [32m+[m[31m-[m
 apps/desktop/tests/ai-service.test.ts              | 122 [32m++++[m[31m-[m
 apps/desktop/tests/repair-eligibility.test.ts      |  37 [32m++[m
 package.json                                       |   2 [32m+[m[31m-[m
 packages/core-ai/src/context/context-builder.ts    |   8 [32m+[m[31m-[m
 packages/core-ai/src/index.ts                      |   1 [32m+[m
 packages/core-ai/src/profiles/profiles.test.ts     |  88 [32m++++[m
 packages/core-ai/src/profiles/profiles.ts          |  14 [32m+[m[31m-[m
 packages/core-ai/src/provider/failure.test.ts      |  62 [32m+++[m
 packages/core-ai/src/provider/failure.ts           |  72 [32m+++[m
 .../core-analysis/src/analyzers/syntax.test.ts     | 469 [32m++++++++++++[m[31m------[m
 packages/core-analysis/src/analyzers/syntax.ts     | 104 [32m+++[m[31m-[m
 packages/core-analysis/src/index.ts                |   2 [32m+[m[31m-[m
 packages/core-analysis/src/parser/grammar-paths.ts |  27 [32m+[m[31m-[m
 .../core-analysis/src/repair/scope-selector.ts     |  29 [32m++[m
 packages/shared-types/src/index.ts                 |   4 [32m+[m
 packages/shared-types/src/repair-support.test.ts   |  43 [32m+[m[31m-[m
 packages/shared-types/src/repair-support.ts        |  20 [32m+[m[31m-[m
 packages/tokens/src/primitives.ts                  |  18 [32m+[m[31m-[m
 tooling/validation/src/generate.test.ts            |  11 [32m+[m
 41 files changed, 1879 insertions(+), 703 deletions(-)
