import { chmodSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { assertInsideWorkspace } from '../../services/fs/path-guard.js';
import type { WorkspaceService } from '../../services/workspace-service.js';
import { registerHandler } from '../router.js';

const HOOK_RELPATH = '.git/hooks/pre-commit';
/** Distinguishes a Fixora-generated hook from any other tool's pre-commit hook already installed
 * there — `hook:status`/`hook:remove` must never claim or touch a hook this app didn't write. */
const MARKER = '# Generated by Fixora — do not edit manually';

function buildHookScript(options: {
  blockOnErrors: boolean;
  blockOnSecurity: boolean;
  stagedOnly: boolean;
}): string {
  // `blockOnSecurity` has nothing to attach to here — same honest gap as the GitHub Actions
  // panel's equivalent toggle: ESLint alone does no security-specific scanning. Kept in the UI,
  // left out of the flags that would otherwise falsely claim it does something.
  const maxWarnings = options.blockOnErrors ? ' --max-warnings 0' : '';
  const diffScope = options.stagedOnly
    ? "git diff --cached --name-only --diff-filter=ACM"
    : 'git ls-files';

  return `#!/bin/sh
# Fixora pre-commit hook
${MARKER}

echo "🔍 Fixora: Analyzing staged files..."

STAGED=$(${diffScope} | grep -E '\\.(js|jsx|ts|tsx)$')

if [ -n "$STAGED" ]; then
  npx eslint $STAGED${maxWarnings}
  if [ $? -ne 0 ]; then
    echo "❌ Fixora: ESLint errors found. Fix before committing."
    exit 1
  fi
fi

echo "✅ Fixora: All checks passed!"
exit 0
`;
}

export function registerHookHandlers(workspaces: WorkspaceService): void {
  registerHandler('hook:install', ({ blockOnErrors, blockOnSecurity, stagedOnly }) => {
    const { rootPath } = workspaces.requireRoot();
    if (!existsSync(join(rootPath, '.git'))) return { installed: false };

    const absolute = assertInsideWorkspace(join(rootPath, HOOK_RELPATH), rootPath);
    mkdirSync(join(rootPath, '.git', 'hooks'), { recursive: true });
    writeFileSync(absolute, buildHookScript({ blockOnErrors, blockOnSecurity, stagedOnly }), 'utf8');
    // No-op (sets the read-only attribute only) on Windows, where there is no executable bit —
    // Git for Windows runs the hook through its own bundled `sh`, which reads the shebang, not
    // the filesystem's permission bits. Real and required on macOS/Linux.
    try {
      chmodSync(absolute, 0o755);
    } catch {
      // Not fatal — a hook git itself cannot execute is a git-level problem, not this call's to
      // report as a failure to install the file, which it did.
    }
    return { installed: true };
  });

  registerHandler('hook:remove', () => {
    const { rootPath } = workspaces.requireRoot();
    const absolute = assertInsideWorkspace(join(rootPath, HOOK_RELPATH), rootPath);
    if (!existsSync(absolute)) return;
    // Never delete a hook this app didn't write — a real risk if another tool (Husky, lint-staged)
    // already owns `.git/hooks/pre-commit` in this repo.
    let content: string;
    try {
      content = readFileSync(absolute, 'utf8');
    } catch {
      return;
    }
    if (content.includes(MARKER)) rmSync(absolute, { force: true });
  });

  registerHandler('hook:status', () => {
    const { rootPath } = workspaces.requireRoot();
    const absolute = assertInsideWorkspace(join(rootPath, HOOK_RELPATH), rootPath);
    if (!existsSync(absolute)) return { installed: false };
    try {
      return { installed: readFileSync(absolute, 'utf8').includes(MARKER) };
    } catch {
      return { installed: false };
    }
  });
}
