import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

/**
 * M0 requires an ADR directory in which "every decision in the architecture doc gets a
 * numbered record". The obvious way to build it is to hand-copy the 28 decisions out of
 * `docs/03-DECISION-REGISTER.md` into 28 files.
 *
 * That would be wrong, and it would be wrong in exactly the way these documents spend their
 * whole length warning about: it creates **two sources of truth for one fact**. Within a
 * month the register and the records disagree, and nobody knows which one the team actually
 * decided.
 *
 * So the records are *generated* from the register, and CI fails if they have drifted
 * (`pnpm gate:adr`). The register stays canonical — it is the document you argue with — and
 * `docs/adr/` is a projection of it, addressable per decision. Editing a file in `docs/adr/`
 * by hand does not change a decision; it breaks the build, which is the correct response to
 * someone trying to change a decision by editing a copy of it.
 */

const REPO_ROOT = join(import.meta.dirname, '..', '..');
const REGISTER = join(REPO_ROOT, 'docs', '03-DECISION-REGISTER.md');
const ADR_DIR = join(REPO_ROOT, 'docs', 'adr');

type Adr = {
  number: string;
  title: string;
  slug: string;
  status: string;
  body: string;
};

const HEADING = /^## ADR-(\d{3}) — (.+)$/;

function slugify(title: string): string {
  return title
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60);
}

function parseRegister(markdown: string): Adr[] {
  const lines = markdown.split(/\r?\n/);
  const adrs: Adr[] = [];

  let current: { number: string; title: string; body: string[] } | null = null;

  for (const line of lines) {
    const heading = HEADING.exec(line);

    if (heading) {
      const [, number, title] = heading;
      if (number === undefined || title === undefined) {
        throw new Error(`Malformed ADR heading in the register: ${line}`);
      }

      if (current) adrs.push(finish(current));
      current = { number, title: title.trim(), body: [] };
      continue;
    }

    if (current) {
      // The register separates records with a horizontal rule. It is a layout device in the
      // register and noise in a standalone record.
      if (line.trim() === '---') continue;
      current.body.push(line);
    }
  }

  if (current) adrs.push(finish(current));
  return adrs;
}

function finish(raw: { number: string; title: string; body: string[] }): Adr {
  const body = raw.body.join('\n').trim();
  const status = /\*\*Status:\*\*\s*\*{0,2}([A-Za-z]+)/.exec(body)?.[1] ?? 'Accepted';

  return {
    number: raw.number,
    title: raw.title,
    slug: slugify(raw.title),
    status,
    body,
  };
}

function render(adr: Adr): string {
  return `# ADR-${adr.number} — ${adr.title}

<!--
  GENERATED from docs/03-DECISION-REGISTER.md by tooling/scripts/sync-adrs.ts.

  Do not edit this file. The register is the source of truth; this is a projection of it, and
  \`pnpm gate:adr\` fails the build if the two disagree. To change a decision, change the
  register (and, if you are superseding this one, say so there) — then run \`pnpm adr:sync\`.
-->

${adr.body}
`;
}

function renderIndex(adrs: Adr[]): string {
  const rows = adrs
    .map((a) => `| [${a.number}](./${a.number}-${a.slug}.md) | ${a.title} | ${a.status} |`)
    .join('\n');

  return `# Architecture Decision Records

Generated from [../03-DECISION-REGISTER.md](../03-DECISION-REGISTER.md) — **that document is the
source of truth.** These files are per-decision records generated from it, so that an ADR can be
linked, cited and diffed on its own. \`pnpm gate:adr\` fails CI if they drift apart.

To add or change a decision: edit the register, then run \`pnpm adr:sync\`.

| # | Decision | Status |
|---|---|---|
${rows}
`;
}

async function main(): Promise<void> {
  const checkOnly = process.argv.includes('--check');

  const register = await readFile(REGISTER, 'utf8');
  const adrs = parseRegister(register);

  if (adrs.length === 0) {
    console.error('No ADRs found in the register. Has its heading format changed?');
    process.exit(1);
  }

  const expected = new Map<string, string>();
  for (const adr of adrs) {
    expected.set(`${adr.number}-${adr.slug}.md`, render(adr));
  }
  expected.set('README.md', renderIndex(adrs));

  if (checkOnly) {
    const drifted: string[] = [];

    let actualFiles: string[];
    try {
      actualFiles = await readdir(ADR_DIR);
    } catch {
      console.error(`✗ docs/adr/ does not exist. Run \`pnpm adr:sync\`.`);
      process.exit(1);
    }

    for (const [name, content] of expected) {
      const actual = await readFile(join(ADR_DIR, name), 'utf8').catch(() => null);
      if (actual !== content) drifted.push(name);
    }
    for (const name of actualFiles) {
      if (!expected.has(name)) drifted.push(`${name} (not in the register)`);
    }

    if (drifted.length > 0) {
      console.error(
        `✗ docs/adr/ has drifted from docs/03-DECISION-REGISTER.md:\n` +
          drifted.map((d) => `    ${d}`).join('\n') +
          `\n\nThe register is the source of truth. If you edited an ADR file directly, move the\n` +
          `change into the register instead. Then run \`pnpm adr:sync\`.\n`,
      );
      process.exit(1);
    }

    console.warn(`✓ ${String(adrs.length)} ADRs in sync with the decision register.`);
    return;
  }

  await rm(ADR_DIR, { recursive: true, force: true });
  await mkdir(ADR_DIR, { recursive: true });
  for (const [name, content] of expected) {
    await writeFile(join(ADR_DIR, name), content, 'utf8');
  }

  console.warn(`✓ wrote ${String(expected.size)} files to docs/adr/`);
}

await main();
