import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { statusNames } from '../src/primitives.js';
import {
  elevation,
  focus,
  fontFamily,
  fontSize,
  fontWeight,
  lineHeight,
  motion,
  radius,
  space,
  zIndex,
} from '../src/scales.js';
import { dark, light, type SemanticColors } from '../src/semantic.js';

const OUT_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'dist');
const PREFIX = '--fx';

function colorVars(c: SemanticColors): string[] {
  const lines: string[] = [];
  const push = (name: string, value: string) => lines.push(`  ${PREFIX}-color-${name}: ${value};`);

  for (const [key, value] of Object.entries(c.bg)) push(`bg-${key}`, value);
  for (const [key, value] of Object.entries(c.text)) push(`text-${kebab(key)}`, value);
  for (const [key, value] of Object.entries(c.border)) push(`border-${key}`, value);
  for (const [key, value] of Object.entries(c.accent)) push(`accent-${kebab(key)}`, value);
  push('focus-ring', c.focus.ring);
  for (const status of statusNames) {
    for (const [key, value] of Object.entries(c.status[status])) {
      // kebab() so `onSolid` becomes `on-solid` — otherwise the emitted var is camelCase,
      // out of step with every other token, and unreachable by the Tailwind mapping.
      push(`status-${status}-${kebab(key)}`, value);
    }
  }
  return lines;
}

function kebab(value: string): string {
  return value.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
}

function staticVars(): string[] {
  const lines: string[] = [];
  const push = (name: string, value: string) => lines.push(`  ${PREFIX}-${name}: ${value};`);

  for (const [key, value] of Object.entries(fontFamily)) push(`font-${key}`, value);
  for (const [key, value] of Object.entries(fontSize)) push(`text-${key}`, value);
  for (const [key, value] of Object.entries(fontWeight)) push(`font-weight-${key}`, value);
  for (const [key, value] of Object.entries(lineHeight)) push(`leading-${key}`, value);
  for (const [key, value] of Object.entries(space)) push(`space-${key}`, value);
  for (const [key, value] of Object.entries(radius)) push(`radius-${key}`, value);
  for (const [key, value] of Object.entries(motion)) push(`motion-${kebab(key)}`, value);
  for (const [key, value] of Object.entries(elevation)) push(`elevation-${key}`, value);
  for (const [key, value] of Object.entries(zIndex)) push(`z-${key}`, value);
  for (const [key, value] of Object.entries(focus)) push(`focus-${kebab(key)}`, value);
  return lines;
}

const header = `/*
 * GENERATED by @fixora/tokens — do not edit.
 * Source of truth: packages/tokens/src. Regenerate with \`pnpm --filter @fixora/tokens build\`.
 *
 * Every readable colour pair below has passed the WCAG contrast gate (Design Review §6.3).
 * Editing this file by hand bypasses that gate, which is the entire reason it exists.
 */
`;

const tokensCss = `${header}
:root {
${staticVars().join('\n')}

  color-scheme: light;
${colorVars(light).join('\n')}
}

:root[data-theme='dark'] {
  color-scheme: dark;
${colorVars(dark).join('\n')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
    color-scheme: dark;
${colorVars(dark)
  .map((line) => `  ${line}`)
  .join('\n')}
  }
}

/*
 * Motion is gated here rather than in each component, because a component that forgets is a
 * component that ships (Design Review §2.4). Durations collapse; nothing else changes.
 */
@media (prefers-reduced-motion: reduce) {
  :root {
    ${PREFIX}-motion-duration-instant: 1ms;
    ${PREFIX}-motion-duration-fast: 1ms;
    ${PREFIX}-motion-duration-normal: 1ms;
    ${PREFIX}-motion-duration-slow: 1ms;
  }
}
`;

/**
 * Tailwind v4 has no JS preset — the theme *is* CSS (`@theme`). This file is the M0
 * deliverable's "Tailwind preset", expressed in the form Tailwind 4 actually accepts, and it
 * is importable by both the desktop app and the website (ADR-019). See ADR-030.
 */
const themeCss = `${header}
@theme inline {
  --color-canvas: var(${PREFIX}-color-bg-canvas);
  --color-raised: var(${PREFIX}-color-bg-raised);
  --color-inset: var(${PREFIX}-color-bg-inset);
  --color-overlay: var(${PREFIX}-color-bg-overlay);
  --color-hover: var(${PREFIX}-color-bg-hover);
  --color-active: var(${PREFIX}-color-bg-active);

  --color-fg: var(${PREFIX}-color-text-primary);
  --color-fg-secondary: var(${PREFIX}-color-text-secondary);
  --color-fg-muted: var(${PREFIX}-color-text-muted);
  --color-on-accent: var(${PREFIX}-color-text-on-accent);

  --color-border-subtle: var(${PREFIX}-color-border-subtle);
  --color-border: var(${PREFIX}-color-border-default);
  --color-border-strong: var(${PREFIX}-color-border-strong);

  --color-accent: var(${PREFIX}-color-accent-solid);
  --color-accent-hover: var(${PREFIX}-color-accent-solid-hover);
  --color-accent-active: var(${PREFIX}-color-accent-solid-active);
  --color-accent-subtle: var(${PREFIX}-color-accent-subtle);
  --color-accent-border: var(${PREFIX}-color-accent-border);
  --color-accent-text: var(${PREFIX}-color-accent-text);

  --color-focus-ring: var(${PREFIX}-color-focus-ring);

${statusNames
  .flatMap((status) => [
    `  --color-${status}: var(${PREFIX}-color-status-${status}-solid);`,
    `  --color-on-${status}: var(${PREFIX}-color-status-${status}-on-solid);`,
    `  --color-${status}-text: var(${PREFIX}-color-status-${status}-text);`,
    `  --color-${status}-subtle: var(${PREFIX}-color-status-${status}-subtle);`,
    `  --color-${status}-border: var(${PREFIX}-color-status-${status}-border);`,
  ])
  .join('\n')}

  --font-sans: var(${PREFIX}-font-sans);
  --font-mono: var(${PREFIX}-font-mono);

${Object.keys(fontSize)
  .map((key) => `  --text-${key}: var(${PREFIX}-text-${key});`)
  .join('\n')}

${Object.keys(radius)
  .map((key) => `  --radius-${key}: var(${PREFIX}-radius-${key});`)
  .join('\n')}

  --ease-entrance: var(${PREFIX}-motion-ease-entrance);
  --ease-exit: var(${PREFIX}-motion-ease-exit);
}
`;

await mkdir(OUT_DIR, { recursive: true });
await writeFile(join(OUT_DIR, 'tokens.css'), tokensCss, 'utf8');
await writeFile(join(OUT_DIR, 'theme.css'), themeCss, 'utf8');

console.warn(`[tokens] wrote ${join(OUT_DIR, 'tokens.css')}`);
console.warn(`[tokens] wrote ${join(OUT_DIR, 'theme.css')}`);
