import { createHash } from 'node:crypto';

/**
 * Pipeline instrumentation — one structured record per repair, covering every stage from problem
 * selection to the Apply gate.
 *
 * This exists because "Apply is disabled and I do not know why" was not answerable from the logs. The
 * verdict was visible; the inputs that produced it were not. Every field here is something that, when
 * it disagrees with another field, explains a wrong verdict:
 *
 *  - **checksums** tell you whether the bytes the model saw, the bytes the verifier checked, and the
 *    bytes on disk are the same bytes. A repair generated against one revision and verified against
 *    another is the classic silent corruption, and a checksum mismatch is the only honest way to see it.
 *  - **request ids** tie a repair, its verification, and its patch together across three processes
 *    (renderer, main, analysis worker). Without them a retry's log lines interleave with the attempt
 *    they replaced and neither can be read.
 *  - **the diagnostic generation** tells you whether the findings the verdict was computed against
 *    still describe the file being verified.
 *
 * It never changes a verdict. It observes, and it is the evidence for whatever the verdict claims.
 */

/** Stable content digest. Short — this is for comparing revisions, not for security. */
export function checksum(content: string): string {
  return createHash('sha256').update(content, 'utf8').digest('hex').slice(0, 12);
}

export interface PipelineTrace {
  /** Correlates every stage of one repair. Generated by the `ai:run` handler. */
  readonly repairRequestId: string;
  /** The verify job id handed to the analysis worker. Null until verification starts. */
  verificationRequestId: string | null;
  /** Identifies one generated patch. A retry or a scope escalation produces a NEW one. */
  patchRequestId: string | null;

  /**
   * The revision of the file this repair is grounded on: the checksum of the bytes read from disk at
   * the start of the run, plus the file's mtime. This is the closest thing the main process has to an
   * editor "document version" — main never sees Monaco's model, so a real editor version would have
   * to be threaded from the renderer, and inventing one here would be a fiction.
   */
  documentChecksum: string | null;
  documentMtimeMs: number | null;

  /**
   * The analysis run the baseline findings came from, and how many there were. When the file has been
   * edited since that run, the baseline describes code that no longer exists and every difference the
   * verifier sees is attributed to the patch.
   */
  diagnosticGeneration: string | null;
  baselineFindingCount: number | null;

  /** The bytes the verifier actually checked, and the replacement that produced them. */
  patchChecksum: string | null;
  patchedFileChecksum: string | null;

  /** The model that answered, which is not always the one configured (failover picks another). */
  configuredModel: string | null;
  usedModel: string | null;

  /** The splice range in force, which scope escalation can widen mid-run. */
  targetRange: string | null;

  /** Terminal state, and the stage that decided it. */
  verdict: string | null;
  applyEnabled: boolean | null;
  decidedBy: string | null;
}

export function newTrace(repairRequestId: string): PipelineTrace {
  return {
    repairRequestId,
    verificationRequestId: null,
    patchRequestId: null,
    documentChecksum: null,
    documentMtimeMs: null,
    diagnosticGeneration: null,
    baselineFindingCount: null,
    patchChecksum: null,
    patchedFileChecksum: null,
    configuredModel: null,
    usedModel: null,
    targetRange: null,
    verdict: null,
    applyEnabled: null,
    decidedBy: null,
  };
}

/**
 * The one place that decides whether the recorded state is self-consistent.
 *
 * Returns the mismatches, in the user's terms. An empty array means every stage of this repair saw
 * the same file at the same revision — which is exactly the claim a verdict implicitly makes and
 * could not previously back up.
 */
export function inconsistencies(trace: PipelineTrace): string[] {
  const problems: string[] = [];
  if (trace.documentChecksum === null) {
    problems.push('No document checksum was recorded — the source revision is unknown.');
  }
  if (trace.patchChecksum === null && trace.verdict !== null) {
    problems.push('A verdict was reached without a recorded patch.');
  }
  if (trace.verificationRequestId === null && trace.verdict !== null && trace.verdict !== 'skipped') {
    problems.push('A verdict was reached without a verification job.');
  }
  return problems;
}

/** Emit the record. One line, greppable, with every field the audit asks for. */
export function emitTrace(trace: PipelineTrace, stage: string): void {
  const problems = inconsistencies(trace);
  console.error(
    `[repair-trace] ${stage} ${JSON.stringify({
      repairRequestId: trace.repairRequestId,
      verificationRequestId: trace.verificationRequestId,
      patchRequestId: trace.patchRequestId,
      documentChecksum: trace.documentChecksum,
      documentMtimeMs: trace.documentMtimeMs,
      diagnosticGeneration: trace.diagnosticGeneration,
      baselineFindingCount: trace.baselineFindingCount,
      patchChecksum: trace.patchChecksum,
      patchedFileChecksum: trace.patchedFileChecksum,
      configuredModel: trace.configuredModel,
      usedModel: trace.usedModel,
      targetRange: trace.targetRange,
      verdict: trace.verdict,
      applyEnabled: trace.applyEnabled,
      decidedBy: trace.decidedBy,
      ...(problems.length > 0 ? { INCONSISTENT: problems } : {}),
    })}`,
  );
}
